version: '3.9'
services:
  backend:
    build:
      context: ./back-end
    ports:
      - "3001:3001"
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./front-end
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - 3000:3000
